# Generated by Django 5.2.5 on 2025-08-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('true_crime', 'True Crime')], max_length=20, null=True),
        ),
    ]
